# Generated by Django 5.2.15 on 2026-09-18 23:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageWhiteboard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('engine', models.CharField(default='excalidraw', max_length=32)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('scene', models.JSONField(default=dict)),
                ('asset_ids', models.JSONField(blank=True, default=list)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('creation_key', models.UUIDField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whiteboards', to='db.page')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_whiteboards', to='db.workspace')),
            ],
            options={
                'db_table': 'page_whiteboards',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('creation_key__isnull', False)), fields=('page', 'creation_key'), name='page_whiteboard_unique_creation_key')],
            },
        ),
    ]
