# Generated by Django 5.2.15 on 2026-09-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    """New whiteboards are Plait scenes (schema v2).

    Only the column defaults change: existing ``excalidraw`` rows keep their
    values and stay readable, but are no longer writable through the API.
    """

    dependencies = [
        ('db', '0124_workspacewhiteboardlibrary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagewhiteboard',
            name='engine',
            field=models.CharField(default='plait', max_length=32),
        ),
        migrations.AlterField(
            model_name='pagewhiteboard',
            name='schema_version',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
