# Generated by Django 5.2.15 on 2026-09-26 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Pages can be verified for a limited time (Wiki)."""

    dependencies = [
        ("db", "0125_alter_pagewhiteboard_engine_and_schema_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="page",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_pages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="verify_expires_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
