
http://{$APP_DOMAIN:do.haivan.one} {
	redir https://{host}{uri} permanent
}

https://{$APP_DOMAIN:do.haivan.one} {
	redir /spaces /spaces/ permanent
	redir /god-mode /god-mode/ permanent
	redir /mcp /mcp/ permanent

	request_body {
		max_size {$FILE_SIZE_LIMIT:5242880}
	}

	reverse_proxy /spaces/* space:3000
	reverse_proxy /god-mode/* admin:3000
	reverse_proxy /live/* live:3000
	reverse_proxy /api/* api:8000
	reverse_proxy /auth/* api:8000
	reverse_proxy /static/* api:8000
	reverse_proxy /{$BUCKET_NAME:uploads}/* plane-minio:9000
	reverse_proxy /{$BUCKET_NAME:uploads} plane-minio:9000
	reverse_proxy /* web:3000
}
